

type Users {
  id: ID! 
  username: String!
  password: String!
  posts: [Posts]!
  created_at: Date!
}

type Posts {
  id:ID!
  title:String!
  user_id: ID!
}


type Query {
  users: [Users]!
}

type Mutation {
 login(username:String!  password: String!): Loggedin!
}

scalar Date
scalar Loggedin